# Generated by Django 4.2.14 on 2024-07-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
