# Generated by Django 4.2.14 on 2024-08-02 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('industry', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('platform', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_offer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand_offer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.brand')),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.creator')),
            ],
        ),
    ]
