# Generated by Django 4.2.14 on 2024-07-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_brandprofie_user_alter_creatorprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofie',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
