# Generated by Django 4.2.14 on 2024-07-20 14:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_brandprofie_active_creatorprofile_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrandProfie',
            new_name='BrandProfile',
        ),
    ]
