# Generated by Django 4.2.14 on 2024-07-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_brandprofie_brandprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='website',
            field=models.URLField(blank=True, max_length=60, null=True),
        ),
    ]
