# Generated by Django 4.2.14 on 2024-07-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_creatorprofile_contact_email_creatorprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
