# Generated by Django 4.2.14 on 2024-07-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_creatorprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
