# Generated by Django 4.2.14 on 2024-07-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_instagramaccountdashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccountdashboard',
            name='profile_link_clicks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
