# Generated by Django 4.2.14 on 2024-07-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_instagramaccountdashboard_profile_link_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccountdashboard',
            name='audience_country',
            field=models.CharField(choices=[('None', 'None'), ('United States', 'United States'), ('Canada', 'Canada'), ('United Kingdom', 'United Kingdom'), ('Australia', 'Australia'), ('India', 'India'), ('Brazil', 'Brazil'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Spain', 'Spain'), ('Japan', 'Japan'), ('South Korea', 'South Korea'), ('China', 'China'), ('Russia', 'Russia'), ('Mexico', 'Mexico'), ('Argentina', 'Argentina'), ('South Africa', 'South Africa'), ('Indonesia', 'Indonesia'), ('Turkey', 'Turkey'), ('Saudi Arabia', 'Saudi Arabia'), ('United Arab Emirates', 'United Arab Emirates'), ('Netherlands', 'Netherlands'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Belgium', 'Belgium'), ('Poland', 'Poland'), ('Norway', 'Norway'), ('Denmark', 'Denmark'), ('Finland', 'Finland'), ('Portugal', 'Portugal'), ('Greece', 'Greece'), ('Ireland', 'Ireland'), ('New Zealand', 'New Zealand'), ('Malaysia', 'Malaysia'), ('Philippines', 'Philippines'), ('Thailand', 'Thailand'), ('Vietnam', 'Vietnam'), ('Singapore', 'Singapore'), ('Hong Kong', 'Hong Kong'), ('Egypt', 'Egypt'), ('Nigeria', 'Nigeria'), ('Kenya', 'Kenya'), ('Israel', 'Israel'), ('Colombia', 'Colombia'), ('Peru', 'Peru'), ('Chile', 'Chile'), ('Pakistan', 'Pakistan'), ('Bangladesh', 'Bangladesh'), ('Ukraine', 'Ukraine'), ('Romania', 'Romania'), ('Hungary', 'Hungary'), ('Czech Republic', 'Czech Republic'), ('Austria', 'Austria')], default='None', max_length=100),
        ),
    ]
