# Generated by Django 4.2.14 on 2024-07-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_instagramaccountdashboard_audience_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramaccountdashboard',
            name='audience_age',
        ),
    ]
