# Generated by Django 4.2.14 on 2024-07-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_instagramaccountdashboard_audience_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='about_brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='brand_email',
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='brand_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
