# Generated by Django 4.2.14 on 2024-07-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_brandprofile_about_brand_brandprofile_brand_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandprofile',
            old_name='about_brand',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='brandprofile',
            old_name='brand_email',
            new_name='email',
        ),
    ]
