# Generated by Django 4.2.14 on 2024-07-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_about_brand_brandprofile_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccountdashboard',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
