# Generated by Django 4.2.14 on 2024-07-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_instagramaccountdashboard_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandproposal',
            name='proposal_status',
            field=models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Paid', 'Paid'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
    ]
