# Generated by Django 4.2.14 on 2024-08-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_brandproposal_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandproposal',
            name='content_type',
            field=models.CharField(choices=[('Reels', 'Reels'), ('Story', 'Story'), ('Post', 'Post'), ('Reels + Post + Story', 'All')], default='Reels + Post + Story', max_length=200),
        ),
    ]
