# Generated by Django 4.2.14 on 2024-08-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_brandproposal_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandproposal',
            name='duration_left',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandproposal',
            name='proposal_status',
            field=models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Paid', 'Paid'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
    ]
