# Generated by Django 4.2.14 on 2024-08-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_brandproposal_duration_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
