# Generated by Django 4.2.14 on 2024-08-02 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_creatorprofile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccountdashboard',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
