# Generated by Django 4.2.14 on 2024-08-04 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_instagramaccountdashboard_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandproposal',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.instagramaccountdashboard'),
        ),
    ]
