# Generated by Django 4.2.14 on 2024-08-04 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_brandproposal_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandproposal',
            name='date_paid',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
