# Generated by Django 4.2.14 on 2024-08-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_brandproposal_date_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandproposal',
            name='date_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
