# Generated by Django 4.2.14 on 2024-08-09 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_brandproposal_date_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandproposal',
            name='proposal_status',
            field=models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Paid', 'Paid'), ('content_approval_pending', 'Content Approval Pending'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Content_Approval_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('verified', models.BooleanField(default=False)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.brandproposal')),
            ],
        ),
    ]
