# Generated by Django 4.2.14 on 2024-08-09 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_brandproposal_proposal_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_approval_images',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.brandproposal'),
        ),
    ]
