# Generated by Django 4.2.14 on 2024-08-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_brandproposal_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccountdashboard',
            name='dashboard_img',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='brandproposal',
            name='proposal_status',
            field=models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Paid', 'Paid'), ('Content Approval Pending', 'Content Approval Pending'), ('Posting Content', 'Posting Content'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
    ]
