# Generated by Django 4.2.14 on 2024-08-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_instagramaccountdashboard_dashboard_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
                ('account_type', models.CharField(blank=True, choices=[('Creator', 'Creator'), ('BRAND', 'Brand')], max_length=100, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=200, null=True)),
                ('code_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
