# Generated by Django 4.2.14 on 2024-08-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_verifyemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyemail',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
