# Generated by Django 4.2.14 on 2024-08-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_verifyemail_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyemail',
            name='account_type',
            field=models.CharField(choices=[('Creator', 'Creator'), ('BRAND', 'Brand')], max_length=100),
        ),
    ]
