# Generated by Django 4.2.14 on 2024-08-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_verifyemail_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
