# Generated by Django 4.2.14 on 2024-08-22 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_brandproposal_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandproposal',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.brandprofile'),
        ),
        migrations.AlterField(
            model_name='brandproposal',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.creatorprofile'),
        ),
    ]
