# Generated by Django 4.2.14 on 2024-09-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_brandproposal_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='contact_email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
