# Generated by Django 4.2.14 on 2024-09-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_creatorprofile_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='email',
            field=models.EmailField(max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='contact_email',
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
    ]
