# Generated by Django 4.2.14 on 2024-10-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_brandprofile_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandprofile',
            old_name='active',
            new_name='subscription_active',
        ),
    ]
