# Generated by Django 4.2.14 on 2024-10-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_rename_active_brandprofile_subscription_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='subscription_months',
            field=models.IntegerField(default=0),
        ),
    ]
