# Generated by Django 4.2.14 on 2024-10-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_brandprofile_subscription_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='subscribed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='subscription_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='subscription_expiry_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
