# Generated by Django 4.2.14 on 2024-10-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_brandprofile_subscribed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='subscription_months',
            field=models.IntegerField(default=1),
        ),
    ]
