# Generated by Django 4.2.14 on 2024-10-31 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_brandprofile_subscription_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccountdashboard',
            name='engagement_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
