# Generated by Django 4.2.14 on 2024-11-01 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_instagramaccountdashboard_engagement_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccountdashboard',
            name='engagement_rate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
