# Generated by Django 4.2.14 on 2024-11-13 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0043_alter_brandprofile_subscription_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccountdashboard',
            name='dashboard_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TiktokDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
