# Generated by Django 4.2.14 on 2024-11-15 10:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_alter_instagramaccountdashboard_dashboard_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiktokdashboard',
            name='user',
        ),
        migrations.AddField(
            model_name='tiktokdashboard',
            name='avatar_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='tiktokdashboard',
            name='creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.creatorprofile'),
        ),
        migrations.AddField(
            model_name='tiktokdashboard',
            name='display_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tiktokdashboard',
            name='follower_count',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tiktokdashboard',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tiktokdashboard',
            name='likes_count',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tiktokdashboard',
            name='open_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tiktokdashboard',
            name='profile_deep_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='tiktokdashboard',
            name='video_count',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
