# Generated by Django 4.2.14 on 2024-11-15 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_remove_tiktokdashboard_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokdashboard',
            name='deal_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tiktokdashboard',
            name='pricing_per_promotion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
