# Generated by Django 4.2.14 on 2024-11-15 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_tiktokdashboard_deal_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokdashboard',
            name='access_token',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tiktokdashboard',
            name='pricing_per_promotion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
