# Generated by Django 4.2.14 on 2024-11-15 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_alter_tiktokdashboard_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokdashboard',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokdashboard',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokdashboard',
            name='follower_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tiktokdashboard',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='tiktokdashboard',
            name='likes_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tiktokdashboard',
            name='open_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokdashboard',
            name='profile_deep_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokdashboard',
            name='video_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
