# Generated by Django 4.2.14 on 2024-11-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_alter_tiktokdashboard_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokdashboard',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
