# Generated by Django 4.2.14 on 2024-11-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_tiktokdashboard_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokdashboard',
            name='display_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
