# Generated by Django 4.2.14 on 2024-11-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_alter_tiktokdashboard_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokdashboard',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokdashboard',
            name='profile_deep_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
