# Generated by Django 4.2.14 on 2024-11-15 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_alter_tiktokdashboard_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokdashboard',
            name='engagement_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
