# Generated by Django 4.2.14 on 2024-11-16 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_tiktokdashboard_engagement_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokdashboard',
            name='engagement_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
