# Generated by Django 4.2.14 on 2024-11-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_alter_tiktokdashboard_engagement_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokdashboard',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
