# Generated by Django 4.2.14 on 2024-11-16 19:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_tiktokdashboard_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiktokProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('timeline_in_days', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('proposed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('product_link', models.URLField(blank=True, null=True)),
                ('proposal_status', models.CharField(blank=True, choices=[('Sent', 'Proposal Sent'), ('Accepted', 'Proposal Accepted'), ('Rejected', 'Proposal Rejected'), ('Paid', 'Deal Paid'), ('Brand Deal Active', 'Deal Active'), ('Confirm Deal Completion', 'Deal Confirm Completion'), ('Completed', 'Deal Completed')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('duration_left', models.DurationField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tiktokdashboard')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.brandprofile')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.creatorprofile')),
            ],
        ),
    ]
