# Generated by Django 4.2.14 on 2024-11-16 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_tiktokproposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandproposal',
            name='item_link',
        ),
        migrations.RemoveField(
            model_name='tiktokproposal',
            name='timeline_in_days',
        ),
        migrations.AddField(
            model_name='brandproposal',
            name='product_link',
            field=models.URLField(blank=True, help_text='Link of Your Product (if any)', null=True),
        ),
        migrations.AddField(
            model_name='tiktokproposal',
            name='timeline',
            field=models.IntegerField(default=3, help_text='Brand Deal Timeline in Days', validators=[django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='brandproposal',
            name='proposed_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='$ Proposed Deal Amount in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='brandproposal',
            name='timeline',
            field=models.IntegerField(default=3, help_text='Brand Deal Timeline in Days', validators=[django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='tiktokproposal',
            name='product_link',
            field=models.URLField(blank=True, help_text='Link of Your Product (if any)', null=True),
        ),
        migrations.AlterField(
            model_name='tiktokproposal',
            name='proposed_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='$ Proposed Deal Amount in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
