# Generated by Django 4.2.14 on 2024-11-17 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_remove_brandproposal_item_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandproposal',
            name='timeline',
            field=models.IntegerField(default=3, help_text='Brand Deal Timeline in Days', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tiktokproposal',
            name='proposal_status',
            field=models.CharField(blank=True, choices=[('Sent', 'Proposal Sent'), ('Rejected', 'Proposal Rejected'), ('Deal Payment Due', 'Deal Payment Due'), ('Brand Deal Active', 'Deal Active'), ('Approve Content', 'Deal Approve Content'), ('Completed', 'Deal Completed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tiktokproposal',
            name='proposed_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='in USD $', max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tiktokproposal',
            name='timeline',
            field=models.IntegerField(default=3, help_text='Brand Deal Timeline in Days', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
