# Generated by Django 4.2.14 on 2024-11-17 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_alter_brandproposal_timeline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokdashboard',
            name='pricing_per_promotion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
