# Generated by Django 4.2.14 on 2024-12-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_alter_tiktokdashboard_pricing_per_promotion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content_Approval_Images',
            new_name='Content_Approval_Media',
        ),
    ]
