# Generated by Django 4.2.14 on 2024-12-06 19:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_rename_content_approval_images_content_approval_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content_approval_media',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='content_approval_media',
            name='url',
        ),
        migrations.AddField(
            model_name='content_approval_media',
            name='ig_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tiktokproposal'),
        ),
        migrations.AddField(
            model_name='content_approval_media',
            name='image',
            field=models.FileField(null=True, upload_to='deal/images/'),
        ),
        migrations.AddField(
            model_name='content_approval_media',
            name='tiktok_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.brandproposal'),
        ),
        migrations.AddField(
            model_name='content_approval_media',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='content_approval_media',
            name='uploaded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content_approval_media',
            name='video',
            field=models.FileField(null=True, upload_to='deal/videos/'),
        ),
    ]
