# Generated by Django 4.2.14 on 2024-12-06 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_remove_content_approval_media_proposal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_approval_media',
            name='ig_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.brandproposal'),
        ),
        migrations.AlterField(
            model_name='content_approval_media',
            name='tiktok_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tiktokproposal'),
        ),
    ]
