# Generated by Django 4.2.14 on 2024-12-07 18:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_alter_content_approval_media_ig_proposal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, choices=[('tiktok', 'Tiktok'), ('instagram', 'Instagram')], max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timeline', models.IntegerField(default=3, help_text='Brand Deal Timeline in Days', validators=[django.core.validators.MinValueValidator(0)])),
                ('proposed_amount', models.DecimalField(decimal_places=2, default=0, help_text='$ Proposed Deal Amount in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('product_link', models.URLField(blank=True, help_text='Link of Your Product (if any)', null=True)),
                ('content_type', models.CharField(choices=[('Reels', 'Ig Reels'), ('Story', 'Ig Story'), ('Post', 'Ig Post'), ('Reels + Post + Story', 'Ig All'), ('Tiktok', 'Tiktok Short')], default='Reels + Post + Story', max_length=200)),
                ('proposal_status', models.CharField(blank=True, choices=[('Sent', 'Proposal Sent'), ('Rejected', 'Proposal Rejected'), ('Accepted', 'Proposal Accepted'), ('Deal Payment Due', 'Deal Payment Due'), ('Paid', 'Deal Paid'), ('Brand Deal Active', 'Deal Active'), ('Content Approval Pending', 'Deal Content Approval Pending'), ('Posting Content', 'Deal Posting Content'), ('Completed', 'Deal Completed')], max_length=200, null=True)),
                ('auto_complete', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('duration_left', models.DurationField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.brandprofile')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.creatorprofile')),
                ('ig_account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.instagramaccountdashboard')),
                ('tiktok_account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tiktokdashboard')),
            ],
        ),
        migrations.RemoveField(
            model_name='tiktokproposal',
            name='account',
        ),
        migrations.RemoveField(
            model_name='tiktokproposal',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='tiktokproposal',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='content_approval_media',
            name='ig_proposal',
        ),
        migrations.RemoveField(
            model_name='content_approval_media',
            name='tiktok_proposal',
        ),
        migrations.DeleteModel(
            name='BrandProposal',
        ),
        migrations.DeleteModel(
            name='TiktokProposal',
        ),
        migrations.AddField(
            model_name='content_approval_media',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.branddeal'),
        ),
    ]
