# Generated by Django 4.2.14 on 2024-12-07 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_branddeal_remove_tiktokproposal_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branddeal',
            name='ig_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.instagramaccountdashboard'),
        ),
        migrations.AlterField(
            model_name='branddeal',
            name='tiktok_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tiktokdashboard'),
        ),
    ]
