# Generated by Django 4.2.14 on 2024-12-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_alter_branddeal_ig_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_approval_media',
            name='autocomplete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='content_approval_media',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branddeal',
            name='content_type',
            field=models.CharField(choices=[('Reels', 'Ig Reels'), ('Story', 'Ig Story'), ('Post', 'Ig Post'), ('Reels + Post + Story', 'Ig All'), ('Tiktok Short', 'Tiktok Short')], default='Reels + Post + Story', max_length=200),
        ),
    ]
