# Generated by Django 4.2.14 on 2024-12-08 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0064_content_approval_media_autocomplete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branddeal',
            name='proposal_status',
            field=models.CharField(blank=True, choices=[('Sent', 'Proposal Sent'), ('Rejected', 'Proposal Rejected'), ('Accepted', 'Proposal Accepted'), ('Deal Payment Due', 'Deal Payment Due'), ('Paid', 'Deal Paid'), ('Brand Deal Active', 'Deal Active'), ('Content Approval Pending', 'Deal Content Approval Pending'), ('Content Approved', 'Deal Content Approved'), ('Posting Content', 'Deal Posting Content'), ('Completed', 'Deal Completed')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='UnsentEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, max_length=400, null=True)),
                ('send_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('param_link', models.URLField(blank=True, null=True)),
                ('issue_raised', models.DateTimeField(auto_now=True)),
                ('issue_fixed', models.DateTimeField(blank=True, null=True)),
                ('send_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_from_account', to=settings.AUTH_USER_MODEL)),
                ('send_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_to_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
