# Generated by Django 4.2.14 on 2024-12-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_alter_branddeal_proposal_status_unsentemails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyemail',
            name='account_type',
            field=models.CharField(choices=[('Creator', 'Creator'), ('BRAND', 'Brand'), ('SIGNUP', 'Signup')], default='SIGNUP', max_length=100),
        ),
    ]
