# Generated by Django 4.2.14 on 2024-12-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_verifyemail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='branddeal',
            name='product_included',
            field=models.BooleanField(default=True, verbose_name='Include Demo Product Shipped to Creator'),
        ),
    ]
