# Generated by Django 4.2.14 on 2025-01-19 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_branddeal_product_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='referral_link_code',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='referral_link_used',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
