# Generated by Django 4.2.14 on 2025-01-19 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_creatorprofile_referral_link_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='referral_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
